baseURL = "https://seclab-osu.github.io/TPEncryption/"
languageCode = "en-us"
title = "Thumbnail Preserving Encryption"

theme = "introduction"
publishDir = "../docs"

[params]

[params.home]
    introHeight = "small"

[markup.goldmark.renderer]
    unsafe= true
